search(contextPath)::="
<div class='results'>
	<div class='container'>
		<div class='result'>
			<div class='col-sm-4'>
	    		<div class='thumbnail'>
	    			<img src='$contextPath$files/img/phone.jpg' width='300px' />
			    			<span class='badge'>5 Photos</span>
	    		</div>
   		 	</div>
   		 	<div class='col-sm-8'>
	    		<div class='result-title'>Apple iPhone 5s 16GB - (FACTORY UNLOCKED)</div>
	    			<h2> description: </h2>
		    		<div class='description'>
		    			When Apple envisioned the iPhone, Apple landed on a remarkably thin and light design. But it's nearly impossible to make a device so thin and so light without sacrificing features or performance.
		    		</div>
				<div class='btn-group tags'>
	    			<button type='button' class='btn btn-success btn-lg'> \$199.99 </button>
	    			<button type='button' class='btn btn-default btn-lg'> Seattle, WA </button>
	    			<button type='button' class='btn btn-primary btn-lg'> Message Seller </button>
				</div>

   		 	</div>
	</div>
</div>	
";